baseURL = "https://hugo-bootstrap.netlify.com"
languageCode = "en-us"
# https://gohugo.io/variables/site/#site-variables-list
title = "Site Title"
theme = "RCF-Bootstrap"
pygmentsCodeFences = true
pygmentsStyle = "vs"

# https://gohugo.io/variables/site/#the-site-params-variable
[params]
    copyright = "Copyright © 2019 Name of Author"
    homepage_banner_title = "Hello."
    homepage_banner_lead = "Title and lead can be modified in config.toml"