baseURL = "http://example.org/"
languageCode = "en-us"
# https://gohugo.io/variables/site/#site-variables-list
title = "Site Title"
theme = "RCF-Bootstrap"

baseurl = "/"

# https://gohugo.io/variables/site/#the-site-params-variable
[params]
    copyright = "Copyright © 2019 Name of Author"
    homepage_banner_text = "Welcome"